# Generated by Django 4.2.11 on 2025-03-18 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stylist",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="availability",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking",
                to="scheduling.availability",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="availability",
            name="stylist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="scheduling.stylist",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="availability",
            unique_together={("stylist", "date")},
        ),
    ]
